"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import {createClient} from "@supabase/supabase-js";
type Saved={id:string;title:string;resume_data:unknown;updated_at:string};
function client(){const u=process.env.NEXT_PUBLIC_SUPABASE_URL;const k=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY||process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;return u&&k?createClient(u,k):null}
export default function SavedResumes(){const [items,setItems]=useState<Saved[]>([]),[loading,setLoading]=useState(true),[signed,setSigned]=useState(false),[error,setError]=useState("");useEffect(()=>{let active=true;const s=client();if(!s){setError("Supabase is not configured.");setLoading(false);return}void(async()=>{const {data:{user}}=await s.auth.getUser();if(!active)return;if(!user){setLoading(false);return}setSigned(true);const {data,error:e}=await s.from("saved_resumes").select("id,title,resume_data,updated_at").eq("user_id",user.id).order("updated_at",{ascending:false});if(!active)return;if(e)setError("Could not load saved resumes.");else setItems((data||[]) as Saved[]);setLoading(false)})();return()=>{active=false}},[]);
async function remove(id:string){if(!window.confirm("Delete this saved resume?"))return;const s=client();if(!s)return;const {error:e}=await s.from("saved_resumes").delete().eq("id",id);if(e)setError("Could not delete resume.");else setItems(v=>v.filter(x=>x.id!==id))}
function openResume(r:Saved){try{localStorage.setItem("tmr-builder-draft",JSON.stringify({data:r.resume_data,step:0}));window.location.href="/resume-builder"}catch{setError("Unable to open resume on this device.")}}
return <main className="min-h-screen bg-[#fbfaf7] px-5 py-12 text-[#28122f]"><div className="mx-auto max-w-4xl"><div className="flex flex-wrap justify-between gap-4"><div><h1 className="text-3xl font-bold">Saved resumes</h1><p className="mt-2 text-[#6b586f]">Keep and reopen resumes from your account.</p></div><Link href="/resume-builder" className="rounded-xl bg-[#28122f] px-5 py-3 font-bold text-white">Resume builder</Link></div>{error&&<p role="alert" className="mt-6 text-red-700">{error}</p>}{loading?<p className="mt-8">Loading…</p>:!signed?<p className="mt-8">Please <Link className="underline" href="/auth">sign in</Link> to view saved resumes.</p>:items.length===0?<p className="mt-8 rounded-2xl bg-white p-6">No saved resumes yet. Create one in Resume Builder.</p>:<div className="mt-8 space-y-3">{items.map(r=><article key={r.id} className="flex flex-wrap items-center justify-between gap-4 rounded-2xl border border-[#eadfeb] bg-white p-5"><div><h2 className="font-bold">{r.title}</h2><p className="text-sm text-[#806f83]">Updated {new Date(r.updated_at).toLocaleDateString()}</p></div><div className="flex gap-3"><button onClick={()=>openResume(r)} className="rounded-lg bg-[#28122f] px-4 py-2 text-white">Open in builder</button><button onClick={()=>void remove(r.id)} className="rounded-lg border px-4 py-2">Delete</button></div></article>)}</div>}</div></main>}
