"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { useParams } from "next/navigation";
import { createClient } from "@supabase/supabase-js";

type Status="applied"|"reviewing"|"shortlisted"|"rejected";
type Applicant={id:string;applicant_id:string;status:Status;created_at:string;profiles:{full_name:string;headline:string;avatar_url:string|null}|null};
function client(){const u=process.env.NEXT_PUBLIC_SUPABASE_URL;const k=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY||process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;return u&&k?createClient(u,k):null;}
export default function ApplicantsPage(){const params=useParams<{id:string}>();const jobId=params.id;const [title,setTitle]=useState("Job");const [items,setItems]=useState<Applicant[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState("");
 async function load(){const s=client();if(!s){setError("Supabase is not configured.");setLoading(false);return;}const {data:a}=await s.auth.getUser();if(!a.user){setError("Sign in as the employer to view applicants.");setLoading(false);return;}const {data:j,error:je}=await s.from("jobs").select("title").eq("id",jobId).eq("employer_id",a.user.id).single();if(je||!j){setError("You can only manage applicants for your own job.");setLoading(false);return;}setTitle(j.title);const {data,error:e}=await s.from("applications").select("id,applicant_id,status,created_at,profiles:applicant_id(full_name,headline,avatar_url)").eq("job_id",jobId).order("created_at",{ascending:false});if(e)setError(e.message);else setItems((data||[]) as unknown as Applicant[]);setLoading(false);}
 useEffect(()=>{void load();},[jobId]);
 async function change(id:string,status:Status){const s=client();if(!s)return;const {error:e}=await s.from("applications").update({status}).eq("id",id);if(e){setError(e.message);return;}setItems(v=>v.map(x=>x.id===id?{...x,status}:x));}
 if(loading)return <main className="min-h-screen bg-[#fbfaf7] p-8">Loading applicants…</main>;
 return <main className="min-h-screen bg-[#fbfaf7] px-5 py-12 text-[#28122f]"><div className="mx-auto max-w-5xl"><Link href="/employer" className="font-bold text-[#84419b]">← Employer dashboard</Link><p className="mt-7 text-sm font-bold uppercase tracking-widest text-[#84419b]">Applicants</p><h1 className="mt-2 text-4xl font-semibold">{title}</h1><p className="mt-2 text-[#6b586f]">Review applicants and move them through your hiring pipeline.</p>{error&&<p className="mt-6 rounded-xl bg-red-50 p-4 text-red-700">{error}</p>}<div className="mt-8 space-y-3">{!error&&items.length===0?<div className="rounded-2xl border bg-white p-7">No applications yet.</div>:items.map(a=><div key={a.id} className="flex flex-wrap items-center justify-between gap-4 rounded-2xl border border-[#eadfeb] bg-white p-5"><div><h2 className="font-semibold">{a.profiles?.full_name||"Applicant"}</h2><p className="mt-1 text-sm text-[#806f83]">{a.profiles?.headline||"TailorMyResume job seeker"}</p><p className="mt-1 text-xs text-[#9a899d]">Applied {new Date(a.created_at).toLocaleDateString()}</p></div><label className="text-xs font-bold uppercase tracking-wide text-[#806f83]">Status<select value={a.status} onChange={e=>void change(a.id,e.target.value as Status)} className="ml-3 rounded-xl border border-[#dfd0e3] bg-white px-3 py-2 text-sm font-bold normal-case text-[#28122f]">{["applied","reviewing","shortlisted","rejected"].map(x=><option key={x} value={x}>{x[0].toUpperCase()+x.slice(1)}</option>)}</select></label></div>)}</div></div></main>}
