"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { useParams, useRouter } from "next/navigation";
import { createClient } from "@supabase/supabase-js";

type Job = { id:string; employer_id:string; title:string; company_name:string; location:string; workplace_type:string; employment_type:string; experience_level:string; description:string; required_skills:string[]; application_url:string|null; status:"draft"|"open"|"closed" };
const field="w-full rounded-xl border border-[#dfd0e3] bg-white px-4 py-3 outline-none focus:border-[#84419b]";
function db(){const u=process.env.NEXT_PUBLIC_SUPABASE_URL,k=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY||process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;return u&&k?createClient(u,k):null}

export default function ManageJob(){
 const {id}=useParams<{id:string}>(); const router=useRouter(); const [job,setJob]=useState<Job|null>(null); const [skills,setSkills]=useState(""); const [busy,setBusy]=useState(false); const [error,setError]=useState("");
 useEffect(()=>{(async()=>{const s=db();if(!s){setError("Supabase is not configured.");return}const {data:a}=await s.auth.getUser();if(!a.user){router.push("/auth");return}const {data,error:e}=await s.from("jobs").select("*").eq("id",id).eq("employer_id",a.user.id).single();if(e){setError("Job not found or you do not have access.");return}setJob(data as Job);setSkills(((data as Job).required_skills||[]).join(", "))})()},[id,router]);
 async function save(status?:Job["status"]){if(!job)return;setBusy(true);setError("");const s=db();if(!s)return;const patch={title:job.title,company_name:job.company_name,location:job.location,workplace_type:job.workplace_type,employment_type:job.employment_type,experience_level:job.experience_level,description:job.description,application_url:job.application_url||null,required_skills:skills.split(",").map(x=>x.trim()).filter(Boolean),...(status?{status,published_at:status==="open"?new Date().toISOString():null}:{})};const {error:e}=await s.from("jobs").update(patch).eq("id",job.id).eq("employer_id",job.employer_id);if(e)setError(e.message);else setJob({...job,...patch} as Job);setBusy(false)}
 async function remove(){if(!job||job.status!=="draft"||!confirm("Delete this draft permanently?"))return;setBusy(true);const s=db();if(!s)return;const {error:e}=await s.from("jobs").delete().eq("id",job.id).eq("employer_id",job.employer_id).eq("status","draft");if(e){setError(e.message);setBusy(false)}else router.push("/employer")}
 if(error&&!job)return <main className="min-h-screen bg-[#fbfaf7] p-8 text-[#28122f]"><div className="mx-auto max-w-2xl"><p>{error}</p><Link href="/employer" className="mt-4 inline-block font-bold text-[#84419b]">Back to employer dashboard</Link></div></main>;
 if(!job)return <main className="min-h-screen bg-[#fbfaf7] p-8">Loading job…</main>;
 const set=(k:keyof Job,v:string)=>setJob({...job,[k]:v});
 return <main className="min-h-screen bg-[#fbfaf7] px-5 py-12 text-[#28122f]"><div className="mx-auto max-w-3xl rounded-3xl border border-[#eadfeb] bg-white p-6 sm:p-9"><div className="flex items-center justify-between gap-4"><Link href="/employer" className="text-sm font-bold text-[#84419b]">← Employer dashboard</Link><span className="rounded-full bg-[#f4edf6] px-3 py-1 text-xs font-bold uppercase">{job.status}</span></div><h1 className="mt-5 text-4xl font-semibold">Manage job</h1>
 <div className="mt-8 grid gap-5 sm:grid-cols-2"><label className="text-sm font-bold">Job title<input className={`${field} mt-2`} value={job.title} onChange={e=>set("title",e.target.value)}/></label><label className="text-sm font-bold">Company<input className={`${field} mt-2`} value={job.company_name} onChange={e=>set("company_name",e.target.value)}/></label><label className="text-sm font-bold">Location<input className={`${field} mt-2`} value={job.location} onChange={e=>set("location",e.target.value)}/></label><label className="text-sm font-bold">Workplace<select className={`${field} mt-2`} value={job.workplace_type} onChange={e=>set("workplace_type",e.target.value)}>{["Remote","Hybrid","On-site"].map(x=><option key={x}>{x}</option>)}</select></label><label className="text-sm font-bold">Employment<select className={`${field} mt-2`} value={job.employment_type} onChange={e=>set("employment_type",e.target.value)}>{["Full-time","Part-time","Contract","Internship"].map(x=><option key={x}>{x}</option>)}</select></label><label className="text-sm font-bold">Experience<select className={`${field} mt-2`} value={job.experience_level} onChange={e=>set("experience_level",e.target.value)}>{["Entry level","Mid level","Senior","Lead"].map(x=><option key={x}>{x}</option>)}</select></label></div>
 <label className="mt-5 block text-sm font-bold">Required skills<input className={`${field} mt-2`} value={skills} onChange={e=>setSkills(e.target.value)}/></label><label className="mt-5 block text-sm font-bold">Application URL<input className={`${field} mt-2`} type="url" value={job.application_url||""} onChange={e=>set("application_url",e.target.value)}/></label><label className="mt-5 block text-sm font-bold">Description<textarea rows={8} className={`${field} mt-2`} value={job.description} onChange={e=>set("description",e.target.value)}/></label>{error&&<p className="mt-5 rounded-xl bg-red-50 p-3 text-sm font-semibold text-red-700">{error}</p>}
 <div className="mt-7 flex flex-wrap gap-3"><button disabled={busy} onClick={()=>save()} className="rounded-xl bg-[#28122f] px-5 py-3 font-bold text-white disabled:opacity-50">Save changes</button>{job.status!=="open"&&<button disabled={busy} onClick={()=>save("open")} className="rounded-xl bg-[#84419b] px-5 py-3 font-bold text-white">Publish</button>}{job.status==="open"&&<button disabled={busy} onClick={()=>save("closed")} className="rounded-xl border border-[#28122f] px-5 py-3 font-bold">Close job</button>}{job.status==="draft"&&<button disabled={busy} onClick={remove} className="rounded-xl border border-red-300 px-5 py-3 font-bold text-red-700">Delete draft</button>}</div>
 </div></main>;
}
